@extends('layouts.course')

@section('heading')
	Welcome to {{{ $_course->code }}}<br><small>{{{ $_course->title }}}</small>
@stop

@section('content')
<div class="row">
	<div class="col-xs-12 text-center" style="font-size:17px">
		Please use the menu items to access the course content.<br><br>
		<span style="color:green">This course website is generated by</span><br>
		{{ HTML::linkRoute('home', 'WebCMS') }} @
		{{ HTML::link('http://www.cse.unsw.edu.au/', 'CSE') }} @
		{{ HTML::link('http://www.unsw.edu.au/', 'UNSW') }}
	</div>
</div>

<br>
<br>
<br>

@include('partials._footer')

@stop
